In [1]:
import pandas as pd
df = pd.read_csv('4. Tenants_ Potential Buyers.csv')
df.head()

,start,end,"Hello, My name is [Interviewer name] from Takwimu Research, a company that conducts market research studies. We are conducting a short survey to understand the property development landscape in Kenya. Your experience is incredibly valuable to us and we would like to get your feedback. This survey will take approximately 15-20 minutes to complete. Your responses will be kept confidential and will only be used for internal improvement purposes. May I request your consent?",Demographics. DEM 1: What is your gender (SELECT ONE),DEM 2: What is your age (SELECT ONE),DEM 3: What is your area of residence,DEM 4: What is your occupation (SELECT ONE),"DEM 5: What is your specific expertise (specify profession), e.g Teacher, Farmer, etc.",DEM 6: What is your highest level of education (SELECT ONE),DEM 7: What is your average monthly household income (combined) (SELECT ONE),...,"A7. What type of property are you most interested in, at the moment? (MULTIPLE CHOICE)/Maisonette","A7. What type of property are you most interested in, at the moment? (MULTIPLE CHOICE)/Office Space","A7. What type of property are you most interested in, at the moment? (MULTIPLE CHOICE)/Retail Shop","A7. What type of property are you most interested in, at the moment? (MULTIPLE CHOICE)/Warehouse","A7. What type of property are you most interested in, at the moment? (MULTIPLE CHOICE)/Other",A8. What are your top three (3) ideal locations to purchase a residential unit?,Give reasons,A9. What are the top three (3) areas to avoid when purchasing a residential unit?,Give reasons.1,_index
0,2025-11-22,2025-11-22,YES,Female,31-34 yrs,Choka,Employed full time,Social worker and community development,Diploma,"KES 100,001-200,000",...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,1.0
1,2025-11-22,2025-11-22,YES,Female,Below 30 yrs,Embakasi North,Employed part-time,Business,Certificate,"Below KES 100,000",...,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,2.0
2,2025-11-22,2025-11-22,YES,Male,31-34 yrs,Embakasi South,Employed full time,Credit Officer,Diploma,"Below KES 100,000",...,0.0,0.0,0.0,1.0,0.0,NaN,NaN,NaN,NaN,3.0
3,2025-11-22,2025-11-22,YES,Male,41-44 yrs,Choka,Employed full time,Computer programmer,Degree,"KES 100,001-200,000",...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,4.0
4,2025-11-22,2025-11-22,YES,Female,41-44 yrs,githurau 44,Entrepreneur/ Business owner/ Self employed,hairdresser,Diploma,"Below KES 100,000",...,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,NaN,5.0

In [2]:
df2 = pd.read_csv('5. Real Estate Agents.csv')
df2.head()

,start,end,"Hello, My name is [Interviewer name] from Takwimu Research, a company that conducts market research studies. We are conducting a short survey to understand the property development landscape in Kenya. Your experience is incredibly valuable to us and we would like to get your feedback. This survey will take approximately 15-20 minutes to complete. Your responses will be kept confidential and will only be used for internal improvement purposes. May I request your consent?",How long have you worked in this position? (Must be more than 2 years),"D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)","D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)/Other","D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)/2 Bedroom Apartment","D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)/3 Bedroom Apartment","D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)/Bedsitter/Studio","D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)/Townhouse",...,"D10. What are current trends in property development (MULTIPLE CHOICE), READ OUT /Green spaces, e.g areas with actual grass, mini garden","D10. What are current trends in property development (MULTIPLE CHOICE), READ OUT /Other",D11. What is the biggest problem you face when building or selling properties? (OPEN ENDED),D12. What is one thing customers are always asking for that is hard to find? (OPEN ENDED),D13. What are some of the future trends in property development (OPEN ENDED),"D14. If one was to seek additional insights into Kenya’s property development landscape, where should they check? (OPEN ENDED)","D15. Looking at Engineering construction firms, which companies are you aware of (OPEN ENDED)","D16. Looking at Property Developers in Kenya, which companies are you aware of?",Phone contact,_index
0,02/12/2025,02/12/2025,YES,5+ years,Affordable Housing Program Other,1,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,02/12/2025,02/12/2025,YES,5+ years,Affordable Housing Program Other,1,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
2,02/12/2025,02/12/2025,YES,5+ years,Affordable Housing Program Other,1,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
3,02/12/2025,02/12/2025,YES,3-5 years,Other,1,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
4,02/12/2025,02/12/2025,YES,3-5 years,Affordable Housing Program Other,1,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5

In [3]:
df.columns.tolist()

['start',
 'end',
 'Hello, My name is [Interviewer name] from Takwimu Research, a company that conducts market research studies. We are conducting a short survey to understand the property development landscape in Kenya. Your experience is incredibly valuable to us and we would like to get your feedback. This survey will take approximately 15-20 minutes to complete. Your responses will be kept confidential and will only be used for internal improvement purposes. May I request your consent?',
 'Demographics.     DEM 1: What is your gender (SELECT ONE)',
 'DEM 2: What is your age (SELECT ONE)',
 'DEM 3: What is your area of residence',
 'DEM 4: What is your occupation (SELECT ONE)',
 'DEM 5:  What is your specific expertise (specify profession), e.g Teacher, Farmer, etc.',
 'DEM 6: What is your highest level of education (SELECT ONE)',
 'DEM 7:  What is your average monthly household income (combined) (SELECT ONE)',
 'DEM 8. Which of the following statements describes your household READ OUT, SINGLE RESPONSE',
 'DEM 9. Are there children living in your household?  SINGLE RESPONSE',
 'DEM 9. What is their age demographic  SINGLE RESPONSE',
 'Section A: Tenants/ Potential Buyers A1. What type of residential unit are you currently living in? (SELECT ONE)',
 'Section A: Tenants/ Potential Buyers A1. What type of residential unit are you currently living in? (SELECT ONE)/1 Bedroom Apartment ',
 'Section A: Tenants/ Potential Buyers A1. What type of residential unit are you currently living in? (SELECT ONE)/2 Bedroom Apartment',
 'Section A: Tenants/ Potential Buyers A1. What type of residential unit are you currently living in? (SELECT ONE)/3 Bedroom Apartment',
 'Section A: Tenants/ Potential Buyers A1. What type of residential unit are you currently living in? (SELECT ONE)/ Bedsitter/Studio ',
 'Section A: Tenants/ Potential Buyers A1. What type of residential unit are you currently living in? (SELECT ONE)/Townhouse ',
 'Section A: Tenants/ Potential Buyers A1. What type of residential unit are you currently living in? (SELECT ONE)/Bungalow ',
 'Section A: Tenants/ Potential Buyers A1. What type of residential unit are you currently living in? (SELECT ONE)/Maisonette ',
 'Section A: Tenants/ Potential Buyers A1. What type of residential unit are you currently living in? (SELECT ONE)/Other',
 'Section A: Tenants/ Potential Buyers A1. What type of residential unit are you currently living in? (SELECT ONE)/1 Bedroom Apartment',
 'Other',
 'Other.1',
 'A2. What considerations do you make before renting a house (OPEN ENDED)',
 'A3. What is your average monthly rent? (SELECT ONE)',
 'A4. What are your top three (3) ideal locations when renting a residential unit?',
 'A5. Looking at interior aesthetics, which of the following would you consider before renting a house. (READ OUT, MULTIPLE CHOICE)',
 'A5. Looking at interior aesthetics, which of the following would you consider before renting a house. (READ OUT, MULTIPLE CHOICE)/Maximizing natural lighting ',
 'A5. Looking at interior aesthetics, which of the following would you consider before renting a house. (READ OUT, MULTIPLE CHOICE)/Flexible spaces with multiple uses, e.g guest bedroom, library, home office ',
 'A5. Looking at interior aesthetics, which of the following would you consider before renting a house. (READ OUT, MULTIPLE CHOICE)/ Neutral colour palettes ',
 'A5. Looking at interior aesthetics, which of the following would you consider before renting a house. (READ OUT, MULTIPLE CHOICE)/Open plan kitchens ',
 'A5. Looking at interior aesthetics, which of the following would you consider before renting a house. (READ OUT, MULTIPLE CHOICE)/Modern and contemporary finishes ',
 'A5. Looking at interior aesthetics, which of the following would you consider before renting a house. (READ OUT, MULTIPLE CHOICE)/ Ample toilet and bathroom spaces ',
 'A5. Looking at interior aesthetics, which of the following would you consider before renting a house. (READ OUT, MULTIPLE CHOICE)/Ample storage (kitchen pantry, closets, etc) ',
 'A5. Looking at interior aesthetics, which of the following would you consider before renting a house. (READ OUT, MULTIPLE CHOICE)/Pet friendly amenities ',
 'A5. Looking at interior aesthetics, which of the following would you consider before renting a house. (READ OUT, MULTIPLE CHOICE)/Spacious balcony ',
 'A5. Looking at interior aesthetics, which of the following would you consider before renting a house. (READ OUT, MULTIPLE CHOICE)/Green spaces, e.g areas with actual grass, mini garden ',
 'A5. Looking at interior aesthetics, which of the following would you consider before renting a house. (READ OUT, MULTIPLE CHOICE)/Flooring solutions ',
 'A5. Looking at interior aesthetics, which of the following would you consider before renting a house. (READ OUT, MULTIPLE CHOICE)/Toddler friendly spaces ',
 'A5. Looking at interior aesthetics, which of the following would you consider before renting a house. (READ OUT, MULTIPLE CHOICE)/Safety, e.g placement of stairs, windows',
 'A5. Looking at interior aesthetics, which of the following would you consider before renting a house. (READ OUT, MULTIPLE CHOICE)/ Easy to clean surfaces ',
 'A5. Looking at interior aesthetics, which of the following would you consider before renting a house. (READ OUT, MULTIPLE CHOICE)/ Other',
 'Other.2',
 'A6. Have you ever considered investing in property? If YES, What is your main motivation? (READ, MULTIPLE CHOICE)',
 'A6. Have you ever considered investing in property? If YES, What is your main motivation? (READ, MULTIPLE CHOICE)/To purchase my first family home ',
 'A6. Have you ever considered investing in property? If YES, What is your main motivation? (READ, MULTIPLE CHOICE)/To upgrade to a better home ',
 'A6. Have you ever considered investing in property? If YES, What is your main motivation? (READ, MULTIPLE CHOICE)/To buy a residential property for rental income  ',
 'A6. Have you ever considered investing in property? If YES, What is your main motivation? (READ, MULTIPLE CHOICE)/To buy a commercial property for rental income ',
 'A6. Have you ever considered investing in property? If YES, What is your main motivation? (READ, MULTIPLE CHOICE)/To find an office/retail space for my business ',
 'A6. Have you ever considered investing in property? If YES, What is your main motivation? (READ, MULTIPLE CHOICE)/ To find a warehouse/ industrial space for my business ',
 'A6. Have you ever considered investing in property? If YES, What is your main motivation? (READ, MULTIPLE CHOICE)/Other',
 'Other.3',
 'A7. What type of property are you most interested in, at the moment?  (PROMPT AFFORDABLE HOUSING)(MULTIPLE CHOICE)',
 'A7. What type of property are you most interested in, at the moment?  (PROMPT AFFORDABLE HOUSING)(MULTIPLE CHOICE)/1 Bedroom Apartment ',
 'A7. What type of property are you most interested in, at the moment?  (PROMPT AFFORDABLE HOUSING)(MULTIPLE CHOICE)/ 2 Bedroom Apartment ',
 'A7. What type of property are you most interested in, at the moment?  (PROMPT AFFORDABLE HOUSING)(MULTIPLE CHOICE)/3 Bedroom Apartment ',
 'A7. What type of property are you most interested in, at the moment?  (PROMPT AFFORDABLE HOUSING)(MULTIPLE CHOICE)/ Bedsitter/Studio ',
 'A7. What type of property are you most interested in, at the moment?  (PROMPT AFFORDABLE HOUSING)(MULTIPLE CHOICE)/Townhouse ',
 'A7. What type of property are you most interested in, at the moment?  (PROMPT AFFORDABLE HOUSING)(MULTIPLE CHOICE)/Bungalow ',
 'A7. What type of property are you most interested in, at the moment?  (PROMPT AFFORDABLE HOUSING)(MULTIPLE CHOICE)/Maisonette ',
 'A7. What type of property are you most interested in, at the moment?  (PROMPT AFFORDABLE HOUSING)(MULTIPLE CHOICE)/Office Space ',
 'A7. What type of property are you most interested in, at the moment?  (PROMPT AFFORDABLE HOUSING)(MULTIPLE CHOICE)/Retail Shop ',
 'A7. What type of property are you most interested in, at the moment?  (PROMPT AFFORDABLE HOUSING)(MULTIPLE CHOICE)/Warehouse ',
 'A7. What type of property are you most interested in, at the moment?  (PROMPT AFFORDABLE HOUSING)(MULTIPLE CHOICE)/Affordable Housing',
 'A7. What type of property are you most interested in, at the moment?  (PROMPT AFFORDABLE HOUSING)(MULTIPLE CHOICE)/Other',
 'Other.4',
 'A8 a). What are your top three (3) ideal locations to purchase a residential unit?',
 'A8. b) Give reasons',
 'A9 a). What are the top three (3) areas to avoid when purchasing a residential unit?',
 'A 9. b)Give reasons',
 'A10. Looking at interior aesthetics, which of the following would you consider when making a decision to purchase a residential unit. (READ OUT, MULTIPLE CHOICE)',
 'A10. Looking at interior aesthetics, which of the following would you consider when making a decision to purchase a residential unit. (READ OUT, MULTIPLE CHOICE)/Maximizing natural lighting ',
 'A10. Looking at interior aesthetics, which of the following would you consider when making a decision to purchase a residential unit. (READ OUT, MULTIPLE CHOICE)/Flexible spaces with multiple uses, e.g guest bedroom, library, home office ',
 'A10. Looking at interior aesthetics, which of the following would you consider when making a decision to purchase a residential unit. (READ OUT, MULTIPLE CHOICE)/ Neutral colour palettes ',
 'A10. Looking at interior aesthetics, which of the following would you consider when making a decision to purchase a residential unit. (READ OUT, MULTIPLE CHOICE)/Open plan kitchens ',
 'A10. Looking at interior aesthetics, which of the following would you consider when making a decision to purchase a residential unit. (READ OUT, MULTIPLE CHOICE)/Modern and contemporary finishes ',
 'A10. Looking at interior aesthetics, which of the following would you consider when making a decision to purchase a residential unit. (READ OUT, MULTIPLE CHOICE)/ Ample toilet and bathroom spaces ',
 'A10. Looking at interior aesthetics, which of the following would you consider when making a decision to purchase a residential unit. (READ OUT, MULTIPLE CHOICE)/Ample storage (kitchen pantry, closets, etc) ',
 'A10. Looking at interior aesthetics, which of the following would you consider when making a decision to purchase a residential unit. (READ OUT, MULTIPLE CHOICE)/Pet friendly amenities ',
 'A10. Looking at interior aesthetics, which of the following would you consider when making a decision to purchase a residential unit. (READ OUT, MULTIPLE CHOICE)/Spacious balcony ',
 'A10. Looking at interior aesthetics, which of the following would you consider when making a decision to purchase a residential unit. (READ OUT, MULTIPLE CHOICE)/Green spaces, e.g areas with actual grass, mini garden ',
 'A10. Looking at interior aesthetics, which of the following would you consider when making a decision to purchase a residential unit. (READ OUT, MULTIPLE CHOICE)/Flooring solutions ',
 'A10. Looking at interior aesthetics, which of the following would you consider when making a decision to purchase a residential unit. (READ OUT, MULTIPLE CHOICE)/Toddler friendly spaces ',
 'A10. Looking at interior aesthetics, which of the following would you consider when making a decision to purchase a residential unit. (READ OUT, MULTIPLE CHOICE)/Safety, e.g placement of stairs, windows',
 'A10. Looking at interior aesthetics, which of the following would you consider when making a decision to purchase a residential unit. (READ OUT, MULTIPLE CHOICE)/ Easy to clean surfaces ',
 'A10. Looking at interior aesthetics, which of the following would you consider when making a decision to purchase a residential unit. (READ OUT, MULTIPLE CHOICE)/ Other',
 'Other.5',
 'A11. What financing model are you likely to consider for property purchase? (MULTIPLE CHOICE), PROBE, READ OUT',
 'A11. What financing model are you likely to consider for property purchase? (MULTIPLE CHOICE), PROBE, READ OUT/Mortgage Loans ',
 'A11. What financing model are you likely to consider for property purchase? (MULTIPLE CHOICE), PROBE, READ OUT/SACCO Loans ',
 'A11. What financing model are you likely to consider for property purchase? (MULTIPLE CHOICE), PROBE, READ OUT/Personal Savings/ Family/ Friends ',
 'A11. What financing model are you likely to consider for property purchase? (MULTIPLE CHOICE), PROBE, READ OUT/Chamma Loans  ',
 'A11. What financing model are you likely to consider for property purchase? (MULTIPLE CHOICE), PROBE, READ OUT/Employer Assisted Housing Schemes ',
 'A11. What financing model are you likely to consider for property purchase? (MULTIPLE CHOICE), PROBE, READ OUT/Developer and Agent-Assisted Plans ',
 'A11. What financing model are you likely to consider for property purchase? (MULTIPLE CHOICE), PROBE, READ OUT/Joint Ventures ',
 'A11. What financing model are you likely to consider for property purchase? (MULTIPLE CHOICE), PROBE, READ OUT/Real Estate Investment Trusts (REITs) ',
 'A11. What financing model are you likely to consider for property purchase? (MULTIPLE CHOICE), PROBE, READ OUT/Rent-to-own ',
 'A11. What financing model are you likely to consider for property purchase? (MULTIPLE CHOICE), PROBE, READ OUT/Other',
 'Other.6',
 'A12. What are the factors to consider before property purchase? (MULTIPLE CHOICE)',
 'A12. What are the factors to consider before property purchase? (MULTIPLE CHOICE)/Price ',
 'A12. What are the factors to consider before property purchase? (MULTIPLE CHOICE)/Architectural design',
 'A12. What are the factors to consider before property purchase? (MULTIPLE CHOICE)/ Interior aesthetics ',
 'A12. What are the factors to consider before property purchase? (MULTIPLE CHOICE)/ Location/ Neighbourhood ',
 'A12. What are the factors to consider before property purchase? (MULTIPLE CHOICE)/Security ',
 'A12. What are the factors to consider before property purchase? (MULTIPLE CHOICE)/Quality of construction materials',
 'A12. What are the factors to consider before property purchase? (MULTIPLE CHOICE)/Financing options ',
 'A12. What are the factors to consider before property purchase? (MULTIPLE CHOICE)/ Amenities (e.g., water, power, parking, internet) ',
 'A12. What are the factors to consider before property purchase? (MULTIPLE CHOICE)/Other',
 'Other.7',
 'A13. What is your motivation towards home ownership? (MULTIPLE CHOICE), PROBE',
 'A13. What is your motivation towards home ownership? (MULTIPLE CHOICE), PROBE/A home is a financial investment ',
 'A13. What is your motivation towards home ownership? (MULTIPLE CHOICE), PROBE/For inheritance and family legacy ',
 'A13. What is your motivation towards home ownership? (MULTIPLE CHOICE), PROBE/Freedom to decorate my house ',
 'A13. What is your motivation towards home ownership? (MULTIPLE CHOICE), PROBE/A permanent dwelling  ',
 'A13. What is your motivation towards home ownership? (MULTIPLE CHOICE), PROBE/Retirement and security ',
 'A13. What is your motivation towards home ownership? (MULTIPLE CHOICE), PROBE/To avoid paying rent ',
 'A13. What is your motivation towards home ownership? (MULTIPLE CHOICE), PROBE/ Establish family values and sense of community in the neighbourhood. ',
 'A13. What is your motivation towards home ownership? (MULTIPLE CHOICE), PROBE/ Other',
 'Other.8',
 'A14.What are some challenges towards home ownership? (READ OUT, MULTIPLE CHOICE), PROBE',
 'A14.What are some challenges towards home ownership? (READ OUT, MULTIPLE CHOICE), PROBE/Inability to make financial commitment ',
 'A14.What are some challenges towards home ownership? (READ OUT, MULTIPLE CHOICE), PROBE/High mortgage rates ',
 'A14.What are some challenges towards home ownership? (READ OUT, MULTIPLE CHOICE), PROBE/ Delay in securing financing ',
 'A14.What are some challenges towards home ownership? (READ OUT, MULTIPLE CHOICE), PROBE/Hidden costs/ charges ',
 'A14.What are some challenges towards home ownership? (READ OUT, MULTIPLE CHOICE), PROBE/Neighbourhood was not ideal ',
 'A14.What are some challenges towards home ownership? (READ OUT, MULTIPLE CHOICE), PROBE/ Large deposit was required ',
 'A14.What are some challenges towards home ownership? (READ OUT, MULTIPLE CHOICE), PROBE/Finding the right property for my budget ',
 'A14.What are some challenges towards home ownership? (READ OUT, MULTIPLE CHOICE), PROBE/Difficulty in getting the right neighbourhood (location) ',
 'A14.What are some challenges towards home ownership? (READ OUT, MULTIPLE CHOICE), PROBE/ Legal and administrative delays ',
 'A14.What are some challenges towards home ownership? (READ OUT, MULTIPLE CHOICE), PROBE/Not enough units to select from ',
 'A14.What are some challenges towards home ownership? (READ OUT, MULTIPLE CHOICE), PROBE/Zoning regulationswere not in line with future needs of the unit ',
 'A14.What are some challenges towards home ownership? (READ OUT, MULTIPLE CHOICE), PROBE/Seller accepted higher offer from a new buyer Other',
 'A14.What are some challenges towards home ownership? (READ OUT, MULTIPLE CHOICE), PROBE/Other',
 'Other.9',
 'A15. Which of the following describes your relationship with your landlord/property manager (READ OUT, MULTIPLE CHOICE)',
 'A15. Which of the following describes your relationship with your landlord/property manager (READ OUT, MULTIPLE CHOICE)/Lack of prompt communication and responsiveness ',
 'A15. Which of the following describes your relationship with your landlord/property manager (READ OUT, MULTIPLE CHOICE)/Repairs and maintenance are hardly done ',
 'A15. Which of the following describes your relationship with your landlord/property manager (READ OUT, MULTIPLE CHOICE)/ The landlord/ property manager is professional and courteous ',
 'A15. Which of the following describes your relationship with your landlord/property manager (READ OUT, MULTIPLE CHOICE)/ Rent increases are arbitrary and unjustified ',
 'A15. Which of the following describes your relationship with your landlord/property manager (READ OUT, MULTIPLE CHOICE)/The landlord is intrusive and disrespectful ',
 'A15. Which of the following describes your relationship with your landlord/property manager (READ OUT, MULTIPLE CHOICE)/The house I currently reside in does not have the best amenities but it is in an ideal location. ',
 'A15. Which of the following describes your relationship with your landlord/property manager (READ OUT, MULTIPLE CHOICE)/The agent/ property manager is rude and disrespectful ',
 'A15. Which of the following describes your relationship with your landlord/property manager (READ OUT, MULTIPLE CHOICE)/There is a history of illegal withholding of security deposits ',
 'A15. Which of the following describes your relationship with your landlord/property manager (READ OUT, MULTIPLE CHOICE)/The landlord has made my stay comfortable ',
 'A15. Which of the following describes your relationship with your landlord/property manager (READ OUT, MULTIPLE CHOICE)/ I am currently considering looking for alternative accommodation. ',
 'A16. Looking at interior aesthetics, which of the following would you consider when making a decision to purchase a residential unit. (READ OUT, MULTIPLE CHOICE)',
 'A16. Looking at interior aesthetics, which of the following would you consider when making a decision to purchase a residential unit. (READ OUT, MULTIPLE CHOICE)/Maximizing natural lighting ',
 'A16. Looking at interior aesthetics, which of the following would you consider when making a decision to purchase a residential unit. (READ OUT, MULTIPLE CHOICE)/Flexible spaces with multiple uses, e.g guest bedroom, library, home office ',
 'A16. Looking at interior aesthetics, which of the following would you consider when making a decision to purchase a residential unit. (READ OUT, MULTIPLE CHOICE)/ Neutral colour palettes ',
 'A16. Looking at interior aesthetics, which of the following would you consider when making a decision to purchase a residential unit. (READ OUT, MULTIPLE CHOICE)/Open plan kitchens ',

In [4]:
df2.columns.tolist()

['start',
 'end',
 'Hello, My name is [Interviewer name] from Takwimu Research, a company that conducts market research studies. We are conducting a short survey to understand the property development landscape in Kenya. Your experience is incredibly valuable to us and we would like to get your feedback. This survey will take approximately 15-20 minutes to complete. Your responses will be kept confidential and will only be used for internal improvement purposes. May I request your consent?',
 'How long have you worked in this position? (Must be more than 2 years)',
 'D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)',
 'D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)/Other',
 'D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)/2 Bedroom Apartment ',
 'D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)/3 Bedroom Apartment  ',
 'D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)/Bedsitter/Studio ',
 'D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)/Townhouse ',
 'D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)/Bungalow ',
 'D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)/Maisonette ',
 'D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)/Office Space ',
 'D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)/ Retail Other',
 'D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)/Warehouse ',
 'D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)/Affordable Housing Program',
 'D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)/Other.1',
 'Other',
 'D2. What properties (residential, commercial, etc) SOLD most in the past 12 months? (MULTIPLE CHOICE)',
 'D2. What properties (residential, commercial, etc) SOLD most in the past 12 months? (MULTIPLE CHOICE)/Other',
 'D2. What properties (residential, commercial, etc) SOLD most in the past 12 months? (MULTIPLE CHOICE)/2 Bedroom Apartment ',
 'D2. What properties (residential, commercial, etc) SOLD most in the past 12 months? (MULTIPLE CHOICE)/3 Bedroom Apartment  ',
 'D2. What properties (residential, commercial, etc) SOLD most in the past 12 months? (MULTIPLE CHOICE)/Bedsitter/Studio ',
 'D2. What properties (residential, commercial, etc) SOLD most in the past 12 months? (MULTIPLE CHOICE)/Townhouse ',
 'D2. What properties (residential, commercial, etc) SOLD most in the past 12 months? (MULTIPLE CHOICE)/Bungalow ',
 'D2. What properties (residential, commercial, etc) SOLD most in the past 12 months? (MULTIPLE CHOICE)/Maisonette ',
 'D2. What properties (residential, commercial, etc) SOLD most in the past 12 months? (MULTIPLE CHOICE)/Office Space ',
 'D2. What properties (residential, commercial, etc) SOLD most in the past 12 months? (MULTIPLE CHOICE)/ Retail Other',
 'D2. What properties (residential, commercial, etc) SOLD most in the past 12 months? (MULTIPLE CHOICE)/Warehouse ',
 'D2. What properties (residential, commercial, etc) SOLD most in the past 12 months? (MULTIPLE CHOICE)/Affordable Housing Program',
 'D2. What properties (residential, commercial, etc) SOLD most in the past 12 months? (MULTIPLE CHOICE)/Other.1',
 'Other.1',
 'D3. What was the SINGLE most popular property (residential, commercial, etc) SOLD in the past 12 months? (SINGLE CHOICE)',
 'Other.2',
 'D4. How many units of this property did you sell in the past 12 months? ',
 'D5. What was the average cost of the most popular units sold in the past 12 months? ',
 'D6. Which property sector has the highest demand  (SELECT ONE)',
 'Other.3',
 'D7. Looking at your clientele for the past 3 years would you say they are mostly….  (READ OUT, MULTIPLE MENTIONS)',
 'D7. Looking at your clientele for the past 3 years would you say they are mostly….  (READ OUT, MULTIPLE MENTIONS)/Local repeat buyers ',
 'D7. Looking at your clientele for the past 3 years would you say they are mostly….  (READ OUT, MULTIPLE MENTIONS)/ First time diaspora clients ',
 'D7. Looking at your clientele for the past 3 years would you say they are mostly….  (READ OUT, MULTIPLE MENTIONS)/ Seasoned real estate investor ',
 'D7. Looking at your clientele for the past 3 years would you say they are mostly….  (READ OUT, MULTIPLE MENTIONS)/The speculator ',
 'D7. Looking at your clientele for the past 3 years would you say they are mostly….  (READ OUT, MULTIPLE MENTIONS)/ Retiree buyer',
 'D7. Looking at your clientele for the past 3 years would you say they are mostly….  (READ OUT, MULTIPLE MENTIONS)/The commercial buyer ',
 'D7. Looking at your clientele for the past 3 years would you say they are mostly….  (READ OUT, MULTIPLE MENTIONS)/ Retiree buyer.1',
 'D7. Looking at your clientele for the past 3 years would you say they are mostly….  (READ OUT, MULTIPLE MENTIONS)/Other',
 'D7. Looking at your clientele for the past 3 years would you say they are mostly….  (READ OUT, MULTIPLE MENTIONS)/Local first time buyers ',
 'Other.4',
 'D8. In the past 12 months, what is the main motivation for people INVESTING in property?  (READ, MULTIPLE CHOICE)',
 'D8. In the past 12 months, what is the main motivation for people INVESTING in property?  (READ, MULTIPLE CHOICE)/To purchase their first family home ',
 'D8. In the past 12 months, what is the main motivation for people INVESTING in property?  (READ, MULTIPLE CHOICE)/To upgrade to a better family home ',
 'D8. In the past 12 months, what is the main motivation for people INVESTING in property?  (READ, MULTIPLE CHOICE)/To buy a residential property for rental income  ',
 'D8. In the past 12 months, what is the main motivation for people INVESTING in property?  (READ, MULTIPLE CHOICE)/To buy a commercial property for rental income ',
 'D8. In the past 12 months, what is the main motivation for people INVESTING in property?  (READ, MULTIPLE CHOICE)/To find an office/retail space for my business ',
 'D8. In the past 12 months, what is the main motivation for people INVESTING in property?  (READ, MULTIPLE CHOICE)/To find a warehouse/ industrial space for my business ',
 'D8. In the past 12 months, what is the main motivation for people INVESTING in property?  (READ, MULTIPLE CHOICE)/Other',
 'Other.5',
 'D9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE',
 'D9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/End-buyer mortgages ',
 'D9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/Construction Finance ',
 'D9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/ Personal Savings/ Family/ Friends ',
 'D9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/ Real Estate Investment Trusts (REITs) ',
 'D9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/Joint Ventures ',
 'D9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/Private Equity & Real Estate Funds ',
 'D9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/ Rent-to-own ',
 'D9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/SACCO loans ',
 'D9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/SACCO loans .1',
 'D9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/Other',
 'D9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/End-buyer mortgages .1',
 'D9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/Construction Finance .1',
 'D9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/Land acquisition loans ',
 'Other.6',
 'D10. From your experience, what are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,',
 'D10. From your experience, what are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,/Financial risks (high interest rates, increased cost of construction, etc) ',
 'D10. From your experience, what are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,/Construction Finance ',
 'D10. From your experience, what are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,/ Market and sales risks ',
 'D10. From your experience, what are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,/Legal risks (title deed fraud, family disputes, etc) ',
 'D10. From your experience, what are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,/Force Majeure (unforeseen calamities) ',
 'D10. From your experience, what are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,/Political instability (post election chaos, government policies, etc) ',
 'D10. From your experience, what are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,/Regulatory delays',
 'D10. From your experience, what are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,/Other',
 'Other.7',
 'D11. In your view what is the ideal development approach/ strategy  to property development  (MULTIPLE CHOICE), READ OUT',
 'D11. In your view what is the ideal development approach/ strategy  to property development  (MULTIPLE CHOICE), READ OUT/Speculative development (building without pre-committed anchor tenant) ',
 'D11. In your view what is the ideal development approach/ strategy  to property development  (MULTIPLE CHOICE), READ OUT/Pre- leased/ Pre-sold development (securing major tenant) ',
 'D11. In your view what is the ideal development approach/ strategy  to property development  (MULTIPLE CHOICE), READ OUT/Institutional investors in real estate, eg ACORN ',
 'D11. In your view what is the ideal development approach/ strategy  to property development  (MULTIPLE CHOICE), READ OUT/Developer + Asset manager model ',
 'D11. In your view what is the ideal development approach/ strategy  to property development  (MULTIPLE CHOICE), READ OUT/Phased development (developing land in stages, e.g phase 1, phase2, phase 3, etc) ',
 'D11. In your view what is the ideal development approach/ strategy  to property development  (MULTIPLE CHOICE), READ OUT/Value -add/ Opportunistic development (acquiring obsolete assets and renovating to increase value) ',
 'D11. In your view what is the ideal development approach/ strategy  to property development  (MULTIPLE CHOICE), READ OUT/ Other',
 'D11. In your view what is the ideal development approach/ strategy  to property development  (MULTIPLE CHOICE), READ OUT/ Other.1',
 'Other.8',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Green buildings (solar installations, etc) ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Amenities eg, swimming pools, lifts, toddler play areas, gyms, etc) ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Mixed Use Developments (MUDs) ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Demand for student accommodation ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Co-living facilities ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Demand for property in satellite towns away from town centres ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Demand for logistics warehousing ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Demand for industrial parks ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Technology integration, ie smart homes ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT / Maximizing natural lighting ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Flexible spaces with multiple uses, e.g guest bedroom, library, home office ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Neutral colour palettes ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Open plan kitchens ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Modern and contemporary finishes ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Pet friendly amenities ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Green spaces, e.g areas with actual grass, mini garden ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Flexibility/ ability to customize spaces as the construction is ongoing',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Other',
 'Other.9',
 'D13. What is the typical structure of a Special Purpose Vehicle (SPV) model in property development? Please talk about shareholding, equity ratio and debt ratios. VERBATIM RESPONSE.',
 'D14. Please describe the team composition of a typical property development project. Please talk about ALL professionals represented in the teamVERBATIM RESPONSE',
 'D15. What is the average size in m2 of a typical property development project?VERBATIM RESPONSE',
 'D16. What is the average cost per m2 of a typical property development project?VERBATIM RESPONSE',
 'D17. What is the revenue per annum for a typical property development project? VERBATIM RESPONSE',
 'D18. What is the Return On Investment (ROI) per annum for a typical property development project? VERBATIM RESPONSE',
 '  D19. What is the biggest problem you face when building or selling properties? (OPEN ENDED)',
 'D20. What is one thing customers are always asking for that is hard to find in a property? (OPEN ENDED)',
 'D21. What are some of the future trends in property development (OPEN ENDED)',
 'D22. If one was to seek additional insights into Kenya’s property development landscape, where should they check? (OPEN ENDED)',
 'D23. Looking at Engineering construction firms, which companies are you aware of (OPEN ENDED)',
 'D24. Looking at Property Developers in Kenya, which companies are you aware of?',
 'Select Category that applies',
 'D1. What was the most popular property (residential, commercial, etc) inquiry in the past 12 months? (SINGLE CHOICE)',
 'D1. What was the most popular property (residential, commercial, etc) inquiry in the past 12 months? (SINGLE CHOICE)/1 Bedroom Apartment ',
 'D1. What was the most popular property (residential, commercial, etc) inquiry in the past 12 months? (SINGLE CHOICE)/2 Bedroom Apartment ',
 'D1. What was the most popular property (residential, commercial, etc) inquiry in the past 12 months? (SINGLE CHOICE)/3 Bedroom Apartment  ',
 'D1. What was the most popular property (residential, commercial, etc) inquiry in the past 12 months? (SINGLE CHOICE)/Bedsitter/Studio ',
 'D1. What was the most popular property (residential, commercial, etc) inquiry in the past 12 months? (SINGLE CHOICE)/Townhouse ',
 'D1. What was the most popular property (residential, commercial, etc) inquiry in the past 12 months? (SINGLE CHOICE)/Bungalow ',
 'D1. What was the most popular property (residential, commercial, etc) inquiry in the past 12 months? (SINGLE CHOICE)/Maisonette ',
 'D1. What was the most popular property (residential, commercial, etc) inquiry in the past 12 months? (SINGLE CHOICE)/Office Space ',
 'D1. What was the most popular property (residential, commercial, etc) inquiry in the past 12 months? (SINGLE CHOICE)/ Retail Other',
 'D1. What was the most popular property (residential, commercial, etc) inquiry in the past 12 months? (SINGLE CHOICE)/Warehouse ',
 'D1. What was the most popular property (residential, commercial, etc) inquiry in the past 12 months? (SINGLE CHOICE)/Other',
 'D1. What was the most popular property (residential, commercial, etc) inquiry in the past 12 months? (SINGLE CHOICE)/Affordable Housing Program',
 'How long have you worked in this position?',
 'D2. What are some of the popular properties (residential, commercial, etc) SOLD in the past 12 months? (MULTIPLE CHOICE)',
 'D2. What are some of the popular properties (residential, commercial, etc) SOLD in the past 12 months? (MULTIPLE CHOICE)/1 Bedroom Apartment ',
 'D2. What are some of the popular properties (residential, commercial, etc) SOLD in the past 12 months? (MULTIPLE CHOICE)/2 Bedroom Apartment ',
 'D2. What are some of the popular properties (residential, commercial, etc) SOLD in the past 12 months? (MULTIPLE CHOICE)/3 Bedroom Apartment  ',
 'D2. What are some of the popular properties (residential, commercial, etc) SOLD in the past 12 months? (MULTIPLE CHOICE)/Bedsitter/Studio ',
 'D2. What are some of the popular properties (residential, commercial, etc) SOLD in the past 12 months? (MULTIPLE CHOICE)/Townhouse ',
 'D2. What are some of the popular properties (residential, commercial, etc) SOLD in the past 12 months? (MULTIPLE CHOICE)/Bungalow ',
 'D2. What are some of the popular properties (residential, commercial, etc) SOLD in the past 12 months? (MULTIPLE CHOICE)/Maisonette ',
 'D2. What are some of the popular properties (residential, commercial, etc) SOLD in the past 12 months? (MULTIPLE CHOICE)/Office Space ',
 'D2. What are some of the popular properties (residential, commercial, etc) SOLD in the past 12 months? (MULTIPLE CHOICE)/ Retail Other',
 'D2. What are some of the popular properties (residential, commercial, etc) SOLD in the past 12 months? (MULTIPLE CHOICE)/Warehouse ',
 'D2. What are some of the popular properties (residential, commercial, etc) SOLD in the past 12 months? (MULTIPLE CHOICE)/Affordable Housing Program',
 'D2. What are some of the popular properties (residential, commercial, etc) SOLD in the past 12 months? (MULTIPLE CHOICE)/Other',
 'D2. What was the most popular property (residential, commercial, etc) sold in the past 12 months? (SINGLE CHOICE)',
 'D2. What was the most popular property (residential, commercial, etc) sold in the past 12 months? (SINGLE CHOICE)/1 Bedroom Apartment ',
 'D2. What was the most popular property (residential, commercial, etc) sold in the past 12 months? (SINGLE CHOICE)/2 Bedroom Apartment ',
 'D2. What was the most popular property (residential, commercial, etc) sold in the past 12 months? (SINGLE CHOICE)/3 Bedroom Apartment  ',
 'D2. What was the most popular property (residential, commercial, etc) sold in the past 12 months? (SINGLE CHOICE)/Bedsitter/Studio ',

In [5]:
import pandas as pd
df3 = pd.read_csv('3. Property Owners_ Investors (1).csv')
df3.columns.tolist()

['start',
 'end',
 'Hello, My name is [Interviewer name] from Takwimu Research, a company that conducts market research studies. We are conducting a short survey to understand the property development landscape in Kenya. Your experience is incredibly valuable to us and we would like to get your feedback. This survey will take approximately 15-20 minutes to complete. Your responses will be kept confidential and will only be used for internal improvement purposes. May I request your consent?',
 'Demographics.     DEM 1: What is your gender (SELECT ONE)',
 'DEM 2: What is your age (SELECT ONE)',
 'DEM 3: What is your area of residence',
 'DEM 4: What is your occupation (SELECT ONE)',
 'DEM 5:  What is your specific expertise (specify profession), e.g Teacher, Farmer, etc.',
 'DEM 6: What is your highest level of education (SELECT ONE)',
 'DEM 7:  What is your average monthly household income (combined) (SELECT ONE)',
 'DEM 8. Which of the following statements describes your household READ OUT, SINGLE RESPONSE',
 'DEM 9. Are there children living in your household?  SINGLE RESPONSE',
 'DEM 9. What is their age demographic  SINGLE RESPONSE',
 'Section B: Property Owners/ Investors B1. What type of residential unit are you currently living in? (SELECT ONE)',
 'Section B: Property Owners/ Investors B1. What type of residential unit are you currently living in? (SELECT ONE)/1 Bedroom Apartment',
 'Section B: Property Owners/ Investors B1. What type of residential unit are you currently living in? (SELECT ONE)/2 Bedroom Apartment',
 'Section B: Property Owners/ Investors B1. What type of residential unit are you currently living in? (SELECT ONE)/3 Bedroom Apartment',
 'Section B: Property Owners/ Investors B1. What type of residential unit are you currently living in? (SELECT ONE)/ Bedsitter/Studio ',
 'Section B: Property Owners/ Investors B1. What type of residential unit are you currently living in? (SELECT ONE)/Townhouse ',
 'Section B: Property Owners/ Investors B1. What type of residential unit are you currently living in? (SELECT ONE)/Bungalow ',
 'Section B: Property Owners/ Investors B1. What type of residential unit are you currently living in? (SELECT ONE)/Maisonette ',
 'Section B: Property Owners/ Investors B1. What type of residential unit are you currently living in? (SELECT ONE)/Other',
 'Other',
 'B2. Do you own the residential unit you currently live in? (SELECT ONE)',
 'B3. Thinking about your first investment in property, what was your main motivation? (MULTIPLE CHOICE)',
 'B3. Thinking about your first investment in property, what was your main motivation? (MULTIPLE CHOICE)/To purchase my first family home ',
 'B3. Thinking about your first investment in property, what was your main motivation? (MULTIPLE CHOICE)/To upgrade to a better home  ',
 'B3. Thinking about your first investment in property, what was your main motivation? (MULTIPLE CHOICE)/To buy a residential property for rental income  ',
 'B3. Thinking about your first investment in property, what was your main motivation? (MULTIPLE CHOICE)/To buy a commercial property for rental income  ',
 'B3. Thinking about your first investment in property, what was your main motivation? (MULTIPLE CHOICE)/To find an office/retail space for my business ',
 'B3. Thinking about your first investment in property, what was your main motivation? (MULTIPLE CHOICE)/ To find a warehouse/ industrial space for my business OTHER',
 'B3. Thinking about your first investment in property, what was your main motivation? (MULTIPLE CHOICE)/Other',
 'Other.1',
 'B4. Have you purchased other properties after your first investment in property? (SELECT ONE)',
 'B5. When was the last time you purchased a property? (SELECT ONE)',
 'B6. What was the cost of the property purchased? (SELECT ONE)',
 'B7. What financing model did you adopt for the most recent property you purchased? (MULTIPLE CHOICE), PROBE',
 'B7. What financing model did you adopt for the most recent property you purchased? (MULTIPLE CHOICE), PROBE/Mortgage Loans ',
 'B7. What financing model did you adopt for the most recent property you purchased? (MULTIPLE CHOICE), PROBE/SACCO Loans ',
 'B7. What financing model did you adopt for the most recent property you purchased? (MULTIPLE CHOICE), PROBE/Personal Savings/ Family/ Friends ',
 'B7. What financing model did you adopt for the most recent property you purchased? (MULTIPLE CHOICE), PROBE/Chamma Loans  ',
 'B7. What financing model did you adopt for the most recent property you purchased? (MULTIPLE CHOICE), PROBE/Employer Assisted Housing Schemes ',
 'B7. What financing model did you adopt for the most recent property you purchased? (MULTIPLE CHOICE), PROBE/Developer and Agent-Assisted Plans ',
 'B7. What financing model did you adopt for the most recent property you purchased? (MULTIPLE CHOICE), PROBE/Joint Ventures ',
 'B7. What financing model did you adopt for the most recent property you purchased? (MULTIPLE CHOICE), PROBE/Real Estate Investment Trusts (REITs) ',
 'B7. What financing model did you adopt for the most recent property you purchased? (MULTIPLE CHOICE), PROBE/Rent-to-own ',
 'B7. What financing model did you adopt for the most recent property you purchased? (MULTIPLE CHOICE), PROBE/Other',
 'Other.2',
 'B8. What are the factors to consider before property purchase? (MULTIPLE CHOICE)',
 'B8. What are the factors to consider before property purchase? (MULTIPLE CHOICE)/Price ',
 'B8. What are the factors to consider before property purchase? (MULTIPLE CHOICE)/Architectural design',
 'B8. What are the factors to consider before property purchase? (MULTIPLE CHOICE)/ Interior aesthetics ',
 'B8. What are the factors to consider before property purchase? (MULTIPLE CHOICE)/ Location/ Neighbourhood ',
 'B8. What are the factors to consider before property purchase? (MULTIPLE CHOICE)/Security ',
 'B8. What are the factors to consider before property purchase? (MULTIPLE CHOICE)/Quality of construction materials',
 'B8. What are the factors to consider before property purchase? (MULTIPLE CHOICE)/Financing options ',
 'B8. What are the factors to consider before property purchase? (MULTIPLE CHOICE)/ Amenities (e.g., water, power, parking, internet) ',
 'B8. What are the factors to consider before property purchase? (MULTIPLE CHOICE)/Other',
 'Other.3',
 'B9. What type of property are you most likely to purchase in the near future? (PROMPT AFFORDABLE HOUSING)',
 'B9. What type of property are you most likely to purchase in the near future? (PROMPT AFFORDABLE HOUSING)/1 Bedroom Apartment ',
 'B9. What type of property are you most likely to purchase in the near future? (PROMPT AFFORDABLE HOUSING)/ 2 Bedroom Apartment ',
 'B9. What type of property are you most likely to purchase in the near future? (PROMPT AFFORDABLE HOUSING)/3 Bedroom Apartment ',
 'B9. What type of property are you most likely to purchase in the near future? (PROMPT AFFORDABLE HOUSING)/Bedsitter/Studio ',
 'B9. What type of property are you most likely to purchase in the near future? (PROMPT AFFORDABLE HOUSING)/Townhouse ',
 'B9. What type of property are you most likely to purchase in the near future? (PROMPT AFFORDABLE HOUSING)/Bungalow ',
 'B9. What type of property are you most likely to purchase in the near future? (PROMPT AFFORDABLE HOUSING)/Maisonette ',
 'B9. What type of property are you most likely to purchase in the near future? (PROMPT AFFORDABLE HOUSING)/Office Space ',
 'B9. What type of property are you most likely to purchase in the near future? (PROMPT AFFORDABLE HOUSING)/Retail Shop ',
 'B9. What type of property are you most likely to purchase in the near future? (PROMPT AFFORDABLE HOUSING)/Warehouse ',
 'B9. What type of property are you most likely to purchase in the near future? (PROMPT AFFORDABLE HOUSING)/Other',
 'B9. What type of property are you most likely to purchase in the near future? (PROMPT AFFORDABLE HOUSING)/Affordable Housing',
 'Other.4',
 'B10. What challenges did you experience when purchasing your most recent unit? (MULTIPLE CHOICE), PROBE',
 'B10. What challenges did you experience when purchasing your most recent unit? (MULTIPLE CHOICE), PROBE/Inability to make financial commitment ',
 'B10. What challenges did you experience when purchasing your most recent unit? (MULTIPLE CHOICE), PROBE/High mortgage rates ',
 'B10. What challenges did you experience when purchasing your most recent unit? (MULTIPLE CHOICE), PROBE/ Delay in securing financing ',
 'B10. What challenges did you experience when purchasing your most recent unit? (MULTIPLE CHOICE), PROBE/Hidden costs/ charges ',
 'B10. What challenges did you experience when purchasing your most recent unit? (MULTIPLE CHOICE), PROBE/Neighbourhood was not ideal ',
 'B10. What challenges did you experience when purchasing your most recent unit? (MULTIPLE CHOICE), PROBE/ Large deposit was required ',
 'B10. What challenges did you experience when purchasing your most recent unit? (MULTIPLE CHOICE), PROBE/Finding the right property for my budget ',
 'B10. What challenges did you experience when purchasing your most recent unit? (MULTIPLE CHOICE), PROBE/Difficulty in getting the right neighbourhood (location) ',
 'B10. What challenges did you experience when purchasing your most recent unit? (MULTIPLE CHOICE), PROBE/ Legal and administrative delays ',
 'B10. What challenges did you experience when purchasing your most recent unit? (MULTIPLE CHOICE), PROBE/Not enough units to select from ',
 'B10. What challenges did you experience when purchasing your most recent unit? (MULTIPLE CHOICE), PROBE/Zoning regulationswere not in line with future needs of the unit ',
 'B10. What challenges did you experience when purchasing your most recent unit? (MULTIPLE CHOICE), PROBE/Seller accepted higher offer from a new buyer Other',
 'B10. What challenges did you experience when purchasing your most recent unit? (MULTIPLE CHOICE), PROBE/Other',
 'Other.5',
 ' B11. a) What are your top three (3) ideal locations when purchasing a residential unit?',
 'B11. b) Give reasons',
 ' B12. a)What are the top three (3) areas to avoid when purchasing a residential unit?',
 'B12. b) Give reasons',
 'B13. What is one thing you wish you had known before purchasing a unit? (OPEN ENDED)',
 ' B14. What is one thing you wish property developers would consider? (OPEN ENDED)',
 'B15. a) Are you planning to buy another property in the next 5 years? (SELECT ONE)',
 'B15. b) If YES, What type of property would it be? (SELECT ONE)',
 'B15. b) If YES, What type of property would it be? (SELECT ONE)/1 Bedroom Apartment ',
 'B15. b) If YES, What type of property would it be? (SELECT ONE)/ 2 Bedroom Apartment ',
 'B15. b) If YES, What type of property would it be? (SELECT ONE)/3 Bedroom Apartment ',
 'B15. b) If YES, What type of property would it be? (SELECT ONE)/Bedsitter/Studio ',
 'B15. b) If YES, What type of property would it be? (SELECT ONE)/Townhouse ',
 'B15. b) If YES, What type of property would it be? (SELECT ONE)/Bungalow ',
 'B15. b) If YES, What type of property would it be? (SELECT ONE)/Maisonette ',
 'B15. b) If YES, What type of property would it be? (SELECT ONE)/Office Space ',
 'B15. b) If YES, What type of property would it be? (SELECT ONE)/Retail Shop ',
 'B15. b) If YES, What type of property would it be? (SELECT ONE)/Warehouse ',
 'B15. b) If YES, What type of property would it be? (SELECT ONE)/Other',
 'B15. b) If YES, What type of property would it be? (SELECT ONE)/Affordable Housing',
 'Other.6',
 'B16. What is important to you when planning to purchase another unit? (MULTIPLE CHOICE)',
 'B16. What is important to you when planning to purchase another unit? (MULTIPLE CHOICE)/Price ',
 'B16. What is important to you when planning to purchase another unit? (MULTIPLE CHOICE)/Architectural design',
 'B16. What is important to you when planning to purchase another unit? (MULTIPLE CHOICE)/ Interior aesthetics ',
 'B16. What is important to you when planning to purchase another unit? (MULTIPLE CHOICE)/ Location/ Neighbourhood ',
 'B16. What is important to you when planning to purchase another unit? (MULTIPLE CHOICE)/Security ',
 'B16. What is important to you when planning to purchase another unit? (MULTIPLE CHOICE)/Quality of construction materials',
 'B16. What is important to you when planning to purchase another unit? (MULTIPLE CHOICE)/Financing options ',
 'B16. What is important to you when planning to purchase another unit? (MULTIPLE CHOICE)/ Amenities (e.g., water, power, parking, internet) ',
 'B16. What is important to you when planning to purchase another unit? (MULTIPLE CHOICE)/Other',
 'Other.7',
 'B17. Looking at interior aesthetics, which of the following have you considered when purchasing a residential unit. (READ OUT, MULTIPLE CHOICE)',
 'B17. Looking at interior aesthetics, which of the following have you considered when purchasing a residential unit. (READ OUT, MULTIPLE CHOICE)/Maximizing natural lighting ',
 'B17. Looking at interior aesthetics, which of the following have you considered when purchasing a residential unit. (READ OUT, MULTIPLE CHOICE)/Flexible spaces with multiple uses, e.g guest bedroom, library, home office ',
 'B17. Looking at interior aesthetics, which of the following have you considered when purchasing a residential unit. (READ OUT, MULTIPLE CHOICE)/ Neutral colour palettes ',
 'B17. Looking at interior aesthetics, which of the following have you considered when purchasing a residential unit. (READ OUT, MULTIPLE CHOICE)/Open plan kitchens ',
 'B17. Looking at interior aesthetics, which of the following have you considered when purchasing a residential unit. (READ OUT, MULTIPLE CHOICE)/Modern and contemporary finishes ',
 'B17. Looking at interior aesthetics, which of the following have you considered when purchasing a residential unit. (READ OUT, MULTIPLE CHOICE)/ Ample toilet and bathroom spaces ',
 'B17. Looking at interior aesthetics, which of the following have you considered when purchasing a residential unit. (READ OUT, MULTIPLE CHOICE)/Ample storage (kitchen pantry, closets, etc) ',
 'B17. Looking at interior aesthetics, which of the following have you considered when purchasing a residential unit. (READ OUT, MULTIPLE CHOICE)/Pet friendly amenities ',
 'B17. Looking at interior aesthetics, which of the following have you considered when purchasing a residential unit. (READ OUT, MULTIPLE CHOICE)/Spacious balcony ',
 'B17. Looking at interior aesthetics, which of the following have you considered when purchasing a residential unit. (READ OUT, MULTIPLE CHOICE)/Green spaces, e.g areas with actual grass, mini garden ',
 'B17. Looking at interior aesthetics, which of the following have you considered when purchasing a residential unit. (READ OUT, MULTIPLE CHOICE)/Ability to customize spaces as the construction is ongoing',
 'B17. Looking at interior aesthetics, which of the following have you considered when purchasing a residential unit. (READ OUT, MULTIPLE CHOICE)/Flooring solutions ',
 'B17. Looking at interior aesthetics, which of the following have you considered when purchasing a residential unit. (READ OUT, MULTIPLE CHOICE)/Toddler friendly spaces ',
 'B17. Looking at interior aesthetics, which of the following have you considered when purchasing a residential unit. (READ OUT, MULTIPLE CHOICE)/Safety, e.g placement of stairs, windows',
 'B17. Looking at interior aesthetics, which of the following have you considered when purchasing a residential unit. (READ OUT, MULTIPLE CHOICE)/ Easy to clean surfaces ',
 'B17. Looking at interior aesthetics, which of the following have you considered when purchasing a residential unit. (READ OUT, MULTIPLE CHOICE)/ Other',
 'B18. From your experience how do you know a credible property developer  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT',
 'B18. From your experience how do you know a credible property developer  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Recommendation from family/ friends/ colleagues ',
 'B18. From your experience how do you know a credible property developer  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Recommendation from SACCOs/ Banks/ Chamma ',
 'B18. From your experience how do you know a credible property developer  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Education and Experience ',
 'B18. From your experience how do you know a credible property developer  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/ Portfolio diversity ',
 'B18. From your experience how do you know a credible property developer  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Financial Standing ',
 'B18. From your experience how do you know a credible property developer  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Evidence of successful projects ',
 'B18. From your experience how do you know a credible property developer  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Verifiable legal and compliance documentation ',
 'B18. From your experience how do you know a credible property developer  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Professional conduct ',
 'B18. From your experience how do you know a credible property developer  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Developers reputation ',
 'B18. From your experience how do you know a credible property developer  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Proven ability to secure funding ',
 'B18. From your experience how do you know a credible property developer  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Willingness to co-create innovative financial solutions ',
 'B18. From your experience how do you know a credible property developer  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Other',
 'Other.8',
 'B19. Looking at Property Developers in Kenya, which companies are you aware of?',
 'THANK RESPONDENT AND CLOSE INTERVIEW',
 'B9. What type of property are you most likely to purchase in the near future? (SELECT ONE)',
 'B9. What type of property are you most likely to purchase in the near future? (SELECT ONE)/1 Bedroom Apartment ',
 'B9. What type of property are you most likely to purchase in the near future? (SELECT ONE)/ 2 Bedroom Apartment ',
 'B9. What type of property are you most likely to purchase in the near future? (SELECT ONE)/3 Bedroom Apartment ',
 'B9. What type of property are you most likely to purchase in the near future? (SELECT ONE)/ Bedsitter/Studio ',
 'B9. What type of property are you most likely to purchase in the near future? (SELECT ONE)/Townhouse ',
 'B9. What type of property are you most likely to purchase in the near future? (SELECT ONE)/Bungalow ',
 'B9. What type of property are you most likely to purchase in the near future? (SELECT ONE)/Maisonette ',
 'B9. What type of property are you most likely to purchase in the near future? (SELECT ONE)/Office Space ',
 'B9. What type of property are you most likely to purchase in the near future? (SELECT ONE)/Retail Shop ',
 'B9. What type of property are you most likely to purchase in the near future? (SELECT ONE)/Warehouse ',
 'B9. What type of property are you most likely to purchase in the near future? (SELECT ONE)/Other',
 '_index']

In [6]:
df4 = pd.read_csv('2. Property Developers.csv')
df4.columns.tolist()

['start',
 'end',
 'Hello, My name is [Interviewer name] from Takwimu Research, a company that conducts market research studies. We are conducting a short survey to understand the property development landscape in Kenya. Your experience is incredibly valuable to us and we would like to get your feedback. This survey will take approximately 15-20 minutes to complete. Your responses will be kept confidential and will only be used for internal improvement purposes. May I request your consent?',
 'Name of Company',
 'Name of Respondent (Optional)',
 'Department (Preferably in Finance, Sales or Engineering departments)',
 'How long have you worked in this position? (Must be more than 2 years)',
 'D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)',
 'D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)/1 Bedroom Apartment ',
 'D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)/Bedsitter/Studio ',
 'D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)/Other',
 'D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)/Bedsitter/Studio .1',
 'D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)/Townhouse ',
 'D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)/Bungalow ',
 'D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)/Maisonette ',
 'D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)/Office Space ',
 'D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)/ Retail Space',
 'D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)/Warehouse ',
 'D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)/Affordable Housing Program',
 'D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)/2 Bedroom Apartment ',
 'D1. What are some of the most common property (residential, commercial, etc) INQUIRIES in the past 12 months? (MULTIPLE CHOICE)/3 Bedroom Apartment  ',
 'Other',
 'D2. What properties (residential, commercial, etc) SOLD most in the past 12 months? (MULTIPLE CHOICE)',
 'D2. What properties (residential, commercial, etc) SOLD most in the past 12 months? (MULTIPLE CHOICE)/1 Bedroom Apartment ',
 'D2. What properties (residential, commercial, etc) SOLD most in the past 12 months? (MULTIPLE CHOICE)/Bedsitter/Studio ',
 'D2. What properties (residential, commercial, etc) SOLD most in the past 12 months? (MULTIPLE CHOICE)/Other',
 'D2. What properties (residential, commercial, etc) SOLD most in the past 12 months? (MULTIPLE CHOICE)/Bedsitter/Studio .1',
 'D2. What properties (residential, commercial, etc) SOLD most in the past 12 months? (MULTIPLE CHOICE)/Townhouse ',
 'D2. What properties (residential, commercial, etc) SOLD most in the past 12 months? (MULTIPLE CHOICE)/Bungalow ',
 'D2. What properties (residential, commercial, etc) SOLD most in the past 12 months? (MULTIPLE CHOICE)/Maisonette ',
 'D2. What properties (residential, commercial, etc) SOLD most in the past 12 months? (MULTIPLE CHOICE)/Office Space ',
 'D2. What properties (residential, commercial, etc) SOLD most in the past 12 months? (MULTIPLE CHOICE)/ Retail Space',
 'D2. What properties (residential, commercial, etc) SOLD most in the past 12 months? (MULTIPLE CHOICE)/Warehouse ',
 'D2. What properties (residential, commercial, etc) SOLD most in the past 12 months? (MULTIPLE CHOICE)/Affordable Housing Program',
 'D2. What properties (residential, commercial, etc) SOLD most in the past 12 months? (MULTIPLE CHOICE)/2 Bedroom Apartment ',
 'D2. What properties (residential, commercial, etc) SOLD most in the past 12 months? (MULTIPLE CHOICE)/3 Bedroom Apartment  ',
 'Other.1',
 'D3. What was the SINGLE most popular property (residential, commercial, etc) SOLD in the past 12 months? (SINGLE CHOICE)',
 'Other.2',
 'D4. How many units of this property did you sell in the past 12 months? ',
 'D5. What was the average cost of the most popular units sold in the past 12 months? ',
 'Other.3',
 'D6. Which property sector has the highest demand  (SELECT ONE)',
 'Other.4',
 'D7. Looking at your clientele for the past 3 years would you say they are mostly….  (READ OUT, MULTIPLE MENTIONS)',
 'D7. Looking at your clientele for the past 3 years would you say they are mostly….  (READ OUT, MULTIPLE MENTIONS)/Local repeat buyers ',
 'D7. Looking at your clientele for the past 3 years would you say they are mostly….  (READ OUT, MULTIPLE MENTIONS)/ First time diaspora clients ',
 'D7. Looking at your clientele for the past 3 years would you say they are mostly….  (READ OUT, MULTIPLE MENTIONS)/ Seasoned real estate investor ',
 'D7. Looking at your clientele for the past 3 years would you say they are mostly….  (READ OUT, MULTIPLE MENTIONS)/The speculator ',
 'D7. Looking at your clientele for the past 3 years would you say they are mostly….  (READ OUT, MULTIPLE MENTIONS)/The speculator .1',
 'D7. Looking at your clientele for the past 3 years would you say they are mostly….  (READ OUT, MULTIPLE MENTIONS)/The commercial buyer ',
 'D7. Looking at your clientele for the past 3 years would you say they are mostly….  (READ OUT, MULTIPLE MENTIONS)/ Retiree buyer',
 'D7. Looking at your clientele for the past 3 years would you say they are mostly….  (READ OUT, MULTIPLE MENTIONS)/Other',
 'D7. Looking at your clientele for the past 3 years would you say they are mostly….  (READ OUT, MULTIPLE MENTIONS)/Local first time buyers ',
 'Other.5',
 'D8. In the past 12 months, what is the main motivation for people INVESTING in property?  (READ, MULTIPLE CHOICE)',
 'D8. In the past 12 months, what is the main motivation for people INVESTING in property?  (READ, MULTIPLE CHOICE)/To purchase their first family home ',
 'D8. In the past 12 months, what is the main motivation for people INVESTING in property?  (READ, MULTIPLE CHOICE)/To upgrade to a better family home ',
 'D8. In the past 12 months, what is the main motivation for people INVESTING in property?  (READ, MULTIPLE CHOICE)/To buy a residential property for rental income  ',
 'D8. In the past 12 months, what is the main motivation for people INVESTING in property?  (READ, MULTIPLE CHOICE)/To buy a commercial property for rental income ',
 'D8. In the past 12 months, what is the main motivation for people INVESTING in property?  (READ, MULTIPLE CHOICE)/To find an office/retail space for my business ',
 'D8. In the past 12 months, what is the main motivation for people INVESTING in property?  (READ, MULTIPLE CHOICE)/To find a warehouse/ industrial space for my business ',
 'D8. In the past 12 months, what is the main motivation for people INVESTING in property?  (READ, MULTIPLE CHOICE)/Other',
 'Other.6',
 'D9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE',
 'D9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/End-buyer mortgages ',
 'D9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/Construction Finance ',
 'D9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/ Personal Savings/ Family/ Friends ',
 'D9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/ Real Estate Investment Trusts (REITs) ',
 'D9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/Joint Ventures ',
 'D9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/Private Equity & Real Estate Funds ',
 'D9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/ Rent-to-own ',
 'D9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/SACCO loans ',
 'D9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/SACCO loans .1',
 'D9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/Other',
 'D9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/Land acquisition loans ',
 'Other.7',
 'D10. From your experience, what are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,',
 'D10. From your experience, what are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,/Financial risks (high interest rates, increased cost of construction, etc) ',
 'D10. From your experience, what are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,/Construction Finance ',
 'D10. From your experience, what are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,/ Market and sales risks ',
 'D10. From your experience, what are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,/Legal risks (title deed fraud, family disputes, etc) ',
 'D10. From your experience, what are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,/Force Majeure (unforeseen calamities) ',
 'D10. From your experience, what are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,/Political instability (post election chaos, government policies, etc) ',
 'D10. From your experience, what are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,/Regulatory delays',
 'D10. From your experience, what are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,/Other',
 'Other.8',
 'D11. In your view what is the ideal development approach/ strategy  to property development  (MULTIPLE CHOICE), READ OUT',
 'D11. In your view what is the ideal development approach/ strategy  to property development  (MULTIPLE CHOICE), READ OUT/Speculative development (building without pre-committed anchor tenant) ',
 'D11. In your view what is the ideal development approach/ strategy  to property development  (MULTIPLE CHOICE), READ OUT/Pre- leased/ Pre-sold development (securing major tenant) ',
 'D11. In your view what is the ideal development approach/ strategy  to property development  (MULTIPLE CHOICE), READ OUT/Institutional investors in real estate, eg ACORN ',
 'D11. In your view what is the ideal development approach/ strategy  to property development  (MULTIPLE CHOICE), READ OUT/Developer + Asset manager model ',
 'D11. In your view what is the ideal development approach/ strategy  to property development  (MULTIPLE CHOICE), READ OUT/Phased development (developing land in stages, e.g phase 1, phase2, phase 3, etc) ',
 'D11. In your view what is the ideal development approach/ strategy  to property development  (MULTIPLE CHOICE), READ OUT/Value -add/ Opportunistic development (acquiring obsolete assets and renovating to increase value) ',
 'D11. In your view what is the ideal development approach/ strategy  to property development  (MULTIPLE CHOICE), READ OUT/Other',
 'Other.9',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Green buildings (solar installations, etc) ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Amenities eg, swimming pools, lifts, toddler play areas, gyms, etc) ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Mixed Use Developments (MUDs) ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Demand for student accommodation ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Co-living facilities ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Demand for property in satellite towns away from town centres ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Demand for logistics warehousing ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Demand for industrial parks ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Technology integration, ie smart homes ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT / Maximizing natural lighting ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Flexible spaces with multiple uses, e.g guest bedroom, library, home office ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Neutral colour palettes ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Open plan kitchens ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Modern and contemporary finishes ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Pet friendly amenities ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Green spaces, e.g areas with actual grass, mini garden ',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Flexibility/ ability to customize spaces as the construction is ongoing',
 'D12. What are current trends in property development  (MULTIPLE CHOICE), READ OUT /Other',
 'Other.10',
 'D13. What is the typical structure of a Special Purpose Vehicle (SPV) model in property development? Please talk about shareholding, equity ratio and debt ratios. VERBATIM RESPONSE.',
 'D14. Please describe the team composition of a typical property development project. Please talk about ALL professionals represented in the teamVERBATIM RESPONSE',
 'D15. What is the average size in m2 of a typical property development project?VERBATIM RESPONSE',
 'D16. What is the average cost per m2 of a typical property development project?VERBATIM RESPONSE',
 'D17. What is the revenue per annum for a typical property development project? VERBATIM RESPONSE',
 'D18. What is the Return On Investment (ROI) per annum for a typical property development project? VERBATIM RESPONSE',
 '  D19. What is the biggest problem you face when building or selling properties? (OPEN ENDED)',
 'D20. What is one thing customers are always asking for that is hard to find in a property? (OPEN ENDED)',
 'D21. What are some of the future trends in property development (OPEN ENDED)',
 'D22. If one was to seek additional insights into Kenya’s property development landscape, where should they check? (OPEN ENDED)',
 'D23. Looking at Engineering construction firms, which companies are you aware of (OPEN ENDED)',
 'D24. Looking at Property Developers in Kenya, which companies are you aware of?',
 'D1. What was the most popular property (residential, commercial, etc) inquiry in the past 12 months? (SINGLE CHOICE)',
 'D1. What was the most popular property (residential, commercial, etc) inquiry in the past 12 months? (SINGLE CHOICE)/1 Bedroom Apartment ',
 'D1. What was the most popular property (residential, commercial, etc) inquiry in the past 12 months? (SINGLE CHOICE)/2 Bedroom Apartment ',
 'D1. What was the most popular property (residential, commercial, etc) inquiry in the past 12 months? (SINGLE CHOICE)/3 Bedroom Apartment  ',
 'D1. What was the most popular property (residential, commercial, etc) inquiry in the past 12 months? (SINGLE CHOICE)/Bedsitter/Studio ',
 'D1. What was the most popular property (residential, commercial, etc) inquiry in the past 12 months? (SINGLE CHOICE)/Townhouse ',
 'D1. What was the most popular property (residential, commercial, etc) inquiry in the past 12 months? (SINGLE CHOICE)/Bungalow ',
 'D1. What was the most popular property (residential, commercial, etc) inquiry in the past 12 months? (SINGLE CHOICE)/Maisonette ',
 'D1. What was the most popular property (residential, commercial, etc) inquiry in the past 12 months? (SINGLE CHOICE)/Office Space ',
 'D1. What was the most popular property (residential, commercial, etc) inquiry in the past 12 months? (SINGLE CHOICE)/ Retail Other',
 'D1. What was the most popular property (residential, commercial, etc) inquiry in the past 12 months? (SINGLE CHOICE)/Warehouse ',
 'D1. What was the most popular property (residential, commercial, etc) inquiry in the past 12 months? (SINGLE CHOICE)/Affordable Housing Program',
 'D1. What was the most popular property (residential, commercial, etc) inquiry in the past 12 months? (SINGLE CHOICE)/Other',
 'D2. What are some of the popular properties (residential, commercial, etc) SOLD in the past 12 months? (MULTIPLE CHOICE)',
 'D2. What are some of the popular properties (residential, commercial, etc) SOLD in the past 12 months? (MULTIPLE CHOICE)/1 Bedroom Apartment ',
 'D2. What are some of the popular properties (residential, commercial, etc) SOLD in the past 12 months? (MULTIPLE CHOICE)/2 Bedroom Apartment ',
 'D2. What are some of the popular properties (residential, commercial, etc) SOLD in the past 12 months? (MULTIPLE CHOICE)/3 Bedroom Apartment  ',
 'D2. What are some of the popular properties (residential, commercial, etc) SOLD in the past 12 months? (MULTIPLE CHOICE)/Bedsitter/Studio ',
 'D2. What are some of the popular properties (residential, commercial, etc) SOLD in the past 12 months? (MULTIPLE CHOICE)/Townhouse ',
 'D2. What are some of the popular properties (residential, commercial, etc) SOLD in the past 12 months? (MULTIPLE CHOICE)/Bungalow ',
 'D2. What are some of the popular properties (residential, commercial, etc) SOLD in the past 12 months? (MULTIPLE CHOICE)/Maisonette ',
 'D2. What are some of the popular properties (residential, commercial, etc) SOLD in the past 12 months? (MULTIPLE CHOICE)/Office Space ',
 'D2. What are some of the popular properties (residential, commercial, etc) SOLD in the past 12 months? (MULTIPLE CHOICE)/ Retail Other',
 'D2. What are some of the popular properties (residential, commercial, etc) SOLD in the past 12 months? (MULTIPLE CHOICE)/Warehouse ',
 'D2. What are some of the popular properties (residential, commercial, etc) SOLD in the past 12 months? (MULTIPLE CHOICE)/Affordable Housing Program',
 'D2. What are some of the popular properties (residential, commercial, etc) SOLD in the past 12 months? (MULTIPLE CHOICE)/Other',
 'D2. What was the most popular property (residential, commercial, etc) sold in the past 12 months? (SINGLE CHOICE)',
 'D2. What was the most popular property (residential, commercial, etc) sold in the past 12 months? (SINGLE CHOICE)/1 Bedroom Apartment ',
 'D2. What was the most popular property (residential, commercial, etc) sold in the past 12 months? (SINGLE CHOICE)/2 Bedroom Apartment ',
 'D2. What was the most popular property (residential, commercial, etc) sold in the past 12 months? (SINGLE CHOICE)/3 Bedroom Apartment  ',
 'D2. What was the most popular property (residential, commercial, etc) sold in the past 12 months? (SINGLE CHOICE)/Bedsitter/Studio ',

In [8]:
df4 = pd.read_csv('1. Banks Financial Institutions.csv')
df4.columns.tolist()

['start',
 'end',
 'Hello, My name is [Interviewer name] from Takwimu Research, a company that conducts market research studies. We are conducting a short survey to understand the property development landscape in Kenya. Your experience is incredibly valuable to us and we would like to get your feedback. This survey will take approximately 15-20 minutes to complete. Your responses will be kept confidential and will only be used for internal improvement purposes. May I request your consent?',
 'Name of Company/ Institution',
 'Select category',
 'Name of Respondent',
 'Department (Asset Financing, Investment Banking, Risk, Corporate, etc)',
 'Job Title',
 'How long have you worked in this position? (Must be more than 2 years)',
 'C1.  Which property development projects (residential, commercial, etc) received the most INQUIRIES  about FINANCING in the past 12 months? MULTIPLE MENTIONS',
 'C1.  Which property development projects (residential, commercial, etc) received the most INQUIRIES  about FINANCING in the past 12 months? MULTIPLE MENTIONS/1 Bedroom Apartments',
 'C1.  Which property development projects (residential, commercial, etc) received the most INQUIRIES  about FINANCING in the past 12 months? MULTIPLE MENTIONS/2 Bedroom Apartments',
 'C1.  Which property development projects (residential, commercial, etc) received the most INQUIRIES  about FINANCING in the past 12 months? MULTIPLE MENTIONS/3 Bedroom Apartments  ',
 'C1.  Which property development projects (residential, commercial, etc) received the most INQUIRIES  about FINANCING in the past 12 months? MULTIPLE MENTIONS/Bedsitter/Studios',
 'C1.  Which property development projects (residential, commercial, etc) received the most INQUIRIES  about FINANCING in the past 12 months? MULTIPLE MENTIONS/Townhouses ',
 'C1.  Which property development projects (residential, commercial, etc) received the most INQUIRIES  about FINANCING in the past 12 months? MULTIPLE MENTIONS/Bungalows ',
 'C1.  Which property development projects (residential, commercial, etc) received the most INQUIRIES  about FINANCING in the past 12 months? MULTIPLE MENTIONS/Maisonettes ',
 'C1.  Which property development projects (residential, commercial, etc) received the most INQUIRIES  about FINANCING in the past 12 months? MULTIPLE MENTIONS/Office Spaces ',
 'C1.  Which property development projects (residential, commercial, etc) received the most INQUIRIES  about FINANCING in the past 12 months? MULTIPLE MENTIONS/Retail Spaces',
 'C1.  Which property development projects (residential, commercial, etc) received the most INQUIRIES  about FINANCING in the past 12 months? MULTIPLE MENTIONS/Warehouses ',
 'C1.  Which property development projects (residential, commercial, etc) received the most INQUIRIES  about FINANCING in the past 12 months? MULTIPLE MENTIONS/Affordable Housing Program',
 'C1.  Which property development projects (residential, commercial, etc) received the most INQUIRIES  about FINANCING in the past 12 months? MULTIPLE MENTIONS/Mixed Use Developments (MUDs) ',
 'C1.  Which property development projects (residential, commercial, etc) received the most INQUIRIES  about FINANCING in the past 12 months? MULTIPLE MENTIONS/Other',
 'C2. What are some of the property development projects (residential, commercial, etc) FINANCED in the past 12 months? MULTIPLE MENTIONS',
 'C2. What are some of the property development projects (residential, commercial, etc) FINANCED in the past 12 months? MULTIPLE MENTIONS/1 Bedroom Apartments',
 'C2. What are some of the property development projects (residential, commercial, etc) FINANCED in the past 12 months? MULTIPLE MENTIONS/2 Bedroom Apartments',
 'C2. What are some of the property development projects (residential, commercial, etc) FINANCED in the past 12 months? MULTIPLE MENTIONS/3 Bedroom Apartments  ',
 'C2. What are some of the property development projects (residential, commercial, etc) FINANCED in the past 12 months? MULTIPLE MENTIONS/Bedsitter/Studios',
 'C2. What are some of the property development projects (residential, commercial, etc) FINANCED in the past 12 months? MULTIPLE MENTIONS/Townhouses ',
 'C2. What are some of the property development projects (residential, commercial, etc) FINANCED in the past 12 months? MULTIPLE MENTIONS/Bungalows ',
 'C2. What are some of the property development projects (residential, commercial, etc) FINANCED in the past 12 months? MULTIPLE MENTIONS/Maisonettes ',
 'C2. What are some of the property development projects (residential, commercial, etc) FINANCED in the past 12 months? MULTIPLE MENTIONS/Office Spaces ',
 'C2. What are some of the property development projects (residential, commercial, etc) FINANCED in the past 12 months? MULTIPLE MENTIONS/Retail Spaces',
 'C2. What are some of the property development projects (residential, commercial, etc) FINANCED in the past 12 months? MULTIPLE MENTIONS/Warehouses ',
 'C2. What are some of the property development projects (residential, commercial, etc) FINANCED in the past 12 months? MULTIPLE MENTIONS/Affordable Housing Program',
 'C2. What are some of the property development projects (residential, commercial, etc) FINANCED in the past 12 months? MULTIPLE MENTIONS/Mixed Use Developments (MUDs) ',
 'C2. What are some of the property development projects (residential, commercial, etc) FINANCED in the past 12 months? MULTIPLE MENTIONS/Other',
 'Other',
 'C3. Which property sectors have the highest demand for funding? (MULTIPLE CHOICE) READ OUT',
 'C3. Which property sectors have the highest demand for funding? (MULTIPLE CHOICE) READ OUT/Affordable Residential (under Ksh 10M)',
 'C3. Which property sectors have the highest demand for funding? (MULTIPLE CHOICE) READ OUT/Medium-Priced Residential (Ksh 10M - 20M) ',
 'C3. Which property sectors have the highest demand for funding? (MULTIPLE CHOICE) READ OUT/High-End Residential (Over Ksh 20M) ',
 'C3. Which property sectors have the highest demand for funding? (MULTIPLE CHOICE) READ OUT/ Commercial Office Space ',
 'C3. Which property sectors have the highest demand for funding? (MULTIPLE CHOICE) READ OUT/Retail Space',
 'C3. Which property sectors have the highest demand for funding? (MULTIPLE CHOICE) READ OUT/ Industrial/Warehouse Space ',
 'C3. Which property sectors have the highest demand for funding? (MULTIPLE CHOICE) READ OUT/Affordable Housing Programme',
 'C3. Which property sectors have the highest demand for funding? (MULTIPLE CHOICE) READ OUT/Other',
 'Other.1',
 'C4. What was the SINGLE most popular property (residential, commercial, etc) FINANCED in the past 12 months? (SINGLE CHOICE)',
 'C5. How many developments of this property did you FINANCE in the past 12 months? ',
 'C6. What is the typical Loan-to-Value (LTV) ratio for a development project? (SELECT ONE)',
 'C7. What are current trends in property development  (MULTIPLE CHOICE), PROBE',
 'C7. What are current trends in property development  (MULTIPLE CHOICE), PROBE/Green buildings  ',
 'C7. What are current trends in property development  (MULTIPLE CHOICE), PROBE/Mixed Use Developments (MUDs) ',
 'C7. What are current trends in property development  (MULTIPLE CHOICE), PROBE/Demand for student accommodation ',
 'C7. What are current trends in property development  (MULTIPLE CHOICE), PROBE/Co-living facilities ',
 'C7. What are current trends in property development  (MULTIPLE CHOICE), PROBE/Demand for property in satellite towns away from town centres ',
 'C7. What are current trends in property development  (MULTIPLE CHOICE), PROBE/Demand for logistics warehousing ',
 'C7. What are current trends in property development  (MULTIPLE CHOICE), PROBE/Technology integration, ie smart homes ',
 'C7. What are current trends in property development  (MULTIPLE CHOICE), PROBE/Affordable Housing Programme',
 'C7. What are current trends in property development  (MULTIPLE CHOICE), PROBE/Other',
 'Other.2',
 'C8. From your experience how do you determine which property developer to finance?  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT',
 'C8. From your experience how do you determine which property developer to finance?  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Recommendation from other developers ',
 'C8. From your experience how do you determine which property developer to finance?  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Recommendation from clients ',
 'C8. From your experience how do you determine which property developer to finance?  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Education and Experience ',
 'C8. From your experience how do you determine which property developer to finance?  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Portfolio diversity ',
 'C8. From your experience how do you determine which property developer to finance?  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Financial Standing ',
 'C8. From your experience how do you determine which property developer to finance?  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Evidence of successful projects ',
 'C8. From your experience how do you determine which property developer to finance?  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Verifiable legal and compliance documentation ',
 'C8. From your experience how do you determine which property developer to finance?  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Professional conduct ',
 'C8. From your experience how do you determine which property developer to finance?  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Developers reputation ',
 'C8. From your experience how do you determine which property developer to finance?  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Proven ability to secure funding ',
 'C8. From your experience how do you determine which property developer to finance?  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Willingness to co-create innovative financial solutions ',
 'C8. From your experience how do you determine which property developer to finance?  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Other',
 'C9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE',
 'C9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/End-buyer mortgages ',
 'C9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/Construction Finance ',
 'C9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/Land acquisition loans ',
 'C9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/Personal Savings/ Family/ Friends ',
 'C9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/ Real Estate Investment Trusts (REITs) ',
 'C9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/Joint Ventures ',
 'C9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/Private Equity & Real Estate Funds ',
 'C9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/ Rent-to-own ',
 'C9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/SACCO loans ',
 'C9. Which financing models are mostly preferred by property developers in Kenya (MULTIPLE CHOICE), PROBE/Other',
 'Other.3',
 'C10. What are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,',
 'C10. What are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,/Financial risks (high interest rates, increased cost of construction, etc) ',
 'C10. What are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,/Construction Finance ',
 'C10. What are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,/ Market and sales risks ',
 'C10. What are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,/ Legal risks (title deed fraud, family disputes, etc) ',
 'C10. What are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,/Force Majeure (unforeseen calamities) ',
 'C10. What are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,/Political instability (post election chaos, government policies, etc) ',
 'C10. What are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,/ Other',
 'C11. In your view what is the ideal development approach/ strategy  to property development  (MULTIPLE CHOICE), READ OUT',
 'C11. In your view what is the ideal development approach/ strategy  to property development  (MULTIPLE CHOICE), READ OUT/Financial risks (high interest rates, increased cost of construction, etc) ',
 'C11. In your view what is the ideal development approach/ strategy  to property development  (MULTIPLE CHOICE), READ OUT/Construction Finance ',
 'C11. In your view what is the ideal development approach/ strategy  to property development  (MULTIPLE CHOICE), READ OUT/ Market and sales risks ',
 'C11. In your view what is the ideal development approach/ strategy  to property development  (MULTIPLE CHOICE), READ OUT/ Legal risks (title deed fraud, family disputes, etc) ',
 'C11. In your view what is the ideal development approach/ strategy  to property development  (MULTIPLE CHOICE), READ OUT/Force Majeure (unforeseen calamities) ',
 'C11. In your view what is the ideal development approach/ strategy  to property development  (MULTIPLE CHOICE), READ OUT/Political instability (post election chaos, government policies, etc) ',
 'C11. In your view what is the ideal development approach/ strategy  to property development  (MULTIPLE CHOICE), READ OUT/ Other',
 'Other.4',
 'C12. What is one thing you would tell property developers to consider before seeking finance options?  (OPEN ENDED)',
 'C13. What is one thing property developers are always looking out for when seeking financing for property development? (OPEN ENDED)',
 'C14. What is one thing customers are always asking for when seeking financing for home ownership? (OPEN ENDED)',
 'C15. Looking at Property Developers in Kenya, which companies are you aware of?',
 'THANK RESPONDENT AND CLOSE INTERVIEW',
 'Department',
 'C1. What is the typical Loan-to-Value (LTV) ratio for a development project? (SELECT ONE)',
 'C2. Which property sectors have the highest demand for funding? (MULTIPLE CHOICE)',
 'C2. Which property sectors have the highest demand for funding? (MULTIPLE CHOICE)/Affordable Residential (under Ksh 10M)',
 'C2. Which property sectors have the highest demand for funding? (MULTIPLE CHOICE)/Medium-Priced Residential (Ksh 10M - 20M) ',
 'C2. Which property sectors have the highest demand for funding? (MULTIPLE CHOICE)/High-End Residential (Over Ksh 20M) ',
 'C2. Which property sectors have the highest demand for funding? (MULTIPLE CHOICE)/ Commercial Office Space ',
 'C2. Which property sectors have the highest demand for funding? (MULTIPLE CHOICE)/ Industrial/Warehouse Space ',
 'C2. Which property sectors have the highest demand for funding? (MULTIPLE CHOICE)/Other',
 'C2. Which property sectors have the highest demand for funding? (MULTIPLE CHOICE)/Affordable Housing Programme',
 'C3. What are current trends in property development  (MULTIPLE CHOICE), PROBE',
 'C3. What are current trends in property development  (MULTIPLE CHOICE), PROBE/Green buildings  ',
 'C3. What are current trends in property development  (MULTIPLE CHOICE), PROBE/Mixed Use Developments (MUDs) ',
 'C3. What are current trends in property development  (MULTIPLE CHOICE), PROBE/Demand for student accommodation ',
 'C3. What are current trends in property development  (MULTIPLE CHOICE), PROBE/Co-living facilities ',
 'C3. What are current trends in property development  (MULTIPLE CHOICE), PROBE/Demand for property in satellite towns away from town centres ',
 'C3. What are current trends in property development  (MULTIPLE CHOICE), PROBE/Demand for logistics warehousing ',
 'C3. What are current trends in property development  (MULTIPLE CHOICE), PROBE/Technology integration, ie smart homes ',
 'C3. What are current trends in property development  (MULTIPLE CHOICE), PROBE/Other',
 'C3. What are current trends in property development  (MULTIPLE CHOICE), PROBE/Affordable Housing Programme',
 'C4. From your experience how do you determine which property developer to finance?  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT',
 'C4. From your experience how do you determine which property developer to finance?  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Recommendation from other developers ',
 'C4. From your experience how do you determine which property developer to finance?  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Recommendation from clients ',
 'C4. From your experience how do you determine which property developer to finance?  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Education and Experience ',
 'C4. From your experience how do you determine which property developer to finance?  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Portfolio diversity ',
 'C4. From your experience how do you determine which property developer to finance?  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Financial Standing ',
 'C4. From your experience how do you determine which property developer to finance?  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Evidence of successful projects ',
 'C4. From your experience how do you determine which property developer to finance?  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Verifiable legal and compliance documentation ',
 'C4. From your experience how do you determine which property developer to finance?  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Professional conduct ',
 'C4. From your experience how do you determine which property developer to finance?  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Developers reputation ',
 'C4. From your experience how do you determine which property developer to finance?  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Proven ability to secure funding ',
 'C4. From your experience how do you determine which property developer to finance?  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Willingness to co-create innovative financial solutions ',
 'C4. From your experience how do you determine which property developer to finance?  (MULTIPLE CHOICE) DO NOT READ OUT, PROMPT/Other',
 'C5. What are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,',
 'C5. What are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,/Financial risks (high interest rates, increased cost of construction, etc) ',
 'C5. What are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,/Construction Finance ',
 'C5. What are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,/ Market and sales risks ',
 'C5. What are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,/ Legal risks (title deed fraud, family disputes, etc) ',
 'C5. What are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,/Force Majeure (unforeseen calamities) ',
 'C5. What are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,/Political instability (post election chaos, government policies, etc) ',
 'C5. What are risks associated with financing property development? (MULTIPLE CHOICE), READ OUT,/ Other',
 'C5. What is one thing you would tell property developers to consider before seeking finance options?  (OPEN ENDED)',
 'C6. What is one thing you would tell property developers to consider before seeking finance options?  (OPEN ENDED)',
 'C6. What is one thing property developers are always looking out for when seeking financing for property development? (OPEN ENDED)',